### ISSUE TITLE
http://vimfest.org/ , Berlin, 16–18 September 2016

### ISSUE THREAD

**Issue by chreekat** [hackerevents/hackerevents#6]
Sorry for lazy issue versus sending PR; I can get to the PR later if nobody else does :)

**Comment by frankrousseau** [comment]
Thank you @chreekat for mentioning that event. A PR would be greatly appreciated (it's a matter of minutes). It's better if it's done by a community member other than me. So I let you or someone else handle it.

**Comment by chreekat** [comment]
NP, I was just getting up to leave when I learned of the project and wanted to jot down a "reminder"! PR inbound.
